name: setoko_chat_package
description: Chat Module For CT CORP.
version: 0.0.1+1
homepage: https://www.ctcorpdigital.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # sendbird sdk
  sendbird_sdk: ^3.1.4

  # state management
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  # inject MobX store
  provider: ^6.0.1

  # utility for date, number and etc
  intl: ^0.17.0

  # draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^0.22.0

  # flutter library to load and cache network images.
  cached_network_image: ^3.1.0

  # plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  mobx_codegen:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ctcorpdigital.setoko_chat_package
        pluginClass: SetokoChatPackagePlugin
      ios:
        pluginClass: SetokoChatPackagePlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/svgs/

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
